version: '2'

services:
  graphdb:
    hostname: graphdb
    image: ontotext/graphdb:10.6.4
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g 
        -Xms1g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.cors.enable=true
        -Dgraphdb.append.request.id.headers=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=500
        -Dreuse.vars.in.subselects=true
    ports:
      - ${GRAPHDB_PORT:-7200}:7200
    networks:
      - traefik-public
  template-skosmos:
    image: registry.diginfra.net/tsd/skosmos:v2.17-1.0-RC1
    environment:
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - SPARQL_ENDPOINT=http://graphdb:7200/repositories/skosmos
      - DATA=${DATA:-/data}
    networks:
      - traefik-public
    ports:
      - '8080:80' #adapt as needed on portainer
    labels:
      - "traefik.enable=true"
      - $TRAEFIK_PORT
      - $TRAEFIK_ENTRYPOINTS
      - $TRAEFIK_HOST
    volumes:
      - gl-skosmos:/data
    depends_on:
      - graphdb
      - template-data
  template-data:
    build:
      context: .
      dockerfile: Dockerfile
#      no_cache: true # needs newer docker-compose.yml version
    volumes:
      - template-data:/data

networks:
  traefik-public:
    external: true

volumes:
  gl-skosmos:
    external: true
