version: '3.5'

services:
  sd-fuseki:
    image: stain/jena-fuseki:latest
    environment:
      - 'ADMIN_PASSWORD=admin'
      - 'JVM_ARGS=-Xmx2g'
      - VIRTUAL_HOST=skosmos-fuseki.sd.di.huc.knaw.nl
      - VIRTUAL_PORT=3030
    networks:
      - sd-skosmos
    ports:
      - '3030:3030'
  sd-skosmos:
    image: registry.huc.knaw.nl/tsd/skosmos:v2.15
    environment:
      - FUSEKI=http://sd-fuseki:3030
      - SPARQL_ENDPOINT=http://sd-fuseki:3030/skosmos/sparql
      - VIRTUAL_HOST=skosmos.sd.di.huc.knaw.nl
      - VIRTUAL_PORT=8080
    networks:
      - sd-skosmos
    ports:
      - '8080:80'
    volumes:
      - ./data:/data
    depends_on:
      - sd-fuseki
networks:
  sd-skosmos:
    external:
      name: nginxproxynetwork
      